### ISSUE TITLE
do not show sub libraries

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafdav#10]
Feature Request: Do not show sub libraries as root folders if user has access to the original library.

see also: (ger) https://forum.seafile-server.org/t/freigegebene-ordner-tauchen-im-webdav-root-auf/1380/4

**Comment by killing** [comment]
Fixed in https://github.com/haiwen/seafdav/commit/d22089c53bd22df78a65ae7c15fc25683adf2dba
