### ISSUE TITLE
Seafdav issue with "Joplin" Android client…

### ISSUE THREAD

**Issue by ludwigvon100** [haiwen/seafdav#20]
Hi,

As described in this [post](https://github.com/laurent22/joplin/issues/383), I am unable to connect my seafdav account on my [android client](https://github.com/laurent22/joplin-android/releases/download/android-v1.0.116/joplin-v1.0.116.apk).
At first sight, I was thinking about a problem in the android app, but it works fine with other webdav servers, so…
Then I installed a [wgsiDAV](https://github.com/mar10/wsgidav/) instance on my server, and I succeeded in login on it.
So, now, I really think about a problem in "Seafdav" rather than the android client…
Which is strange because seadav seems to be a fork of wsgiDAV?!…

Any idea about this strange behaviour?

**Comment by AlekseyMko** [comment]
I have the same issue on Android. I tried with different applications
In the same time, I can connect via Finder from Mac

**Comment by AlekseyMko** [comment]
This is a screenshot of Joplin's error:

![screenshot_2018-07-18-12-47-44-646_net cozic joplin](https://user-images.githubusercontent.com/11870760/42878050-5c85cf72-8a94-11e8-8a2f-7d1045f5acf4.png)

**Comment by AlekseyMko** [comment]
My seafdav is deployed under Nginx with the default configuration from manual on raspberry pi

**Comment by shoeper** [comment]
You can try to set a referer header using nginx.
