### ISSUE TITLE
seafdav does not work

### ISSUE THREAD

**Issue by shady2k** [haiwen/seafdav#27]
seafdav does not work. Server version 7.0.3. 
https://download.seadrive.org/seafile-server_7.0.3_x86-64.tar.gz

Config:
```
[WEBDAV]
enabled = true
port = 8081
fastcgi = false
share_name = /seafdav
```

In log file after restart:
```
[2019-07-15 14:01:33,715]:  Init seahub database...
[2019-07-15 14:01:33,715]:  Failed to init seahub db: No module named seahub_settings.
```

Server returns HTTP error 500.

**Comment by caixiangyue** [comment]
Check if seahub_settings.py exists in conf directory.

**Comment by shady2k** [comment]
> Check if seahub_settings.py exists in conf directory.

Yes, file exists.

**Comment by caixiangyue** [comment]
can you tell me detailed reproduce step?

**Comment by shady2k** [comment]
1. Install server version 7.0.3
2. Create config seafdav.conf
```
[WEBDAV]
enabled = true
port = 8081
fastcgi = false
share_name = /seafdav
```
3. Set up nginx
4. Restart Seafile

**Comment by shady2k** [comment]
After upgrade server to version 7.0.4, no records in seafdav.log at all.

**Comment by sinni800** [comment]
Seafdav is gone for me too, it just simply doesn't start anymore. I can't find a trace of it since upgrading to 7.0.4 from 6.3.4

**Comment by cpstar** [comment]
this may be a bug.
because wsgi/addons/seafile/seahub_db.py import seahub_settings module and failed. I've made a  symbolic link from the conf/seahub_settings.py to the addons, at least the error of 'Failed to init seahub db' never shows up. However it still not working.
I'm using nginx, nginx returns 502.

**Comment by RasmusAaen** [comment]
Same problem here - running Seafile server 7.0.5 behind Apache. 

@caixiangyue - any news on this? It seems to be a general problem.

**Comment by caixiangyue** [comment]
> Same problem here - running Seafile server 7.0.5 behind Apache.
> 
> @caixiangyue - any news on this? It seems to be a general problem.
> 
> Update: I upgraded to v. 7.1.3 - that fixed the problem, so I guess It's OK now.

Yes, 7.1.X is available.
