### ISSUE TITLE
gunicorn timeout needs to be increased

### ISSUE THREAD

**Issue by eruditewriter** [haiwen/seafdav#35]
The Gunicorn timeout is left at the default (30s I believe). This means that for some larger data sets and depending on client implementation the worker thread may be left idle and the stream will reset and the operation will not complete.

In _wsgidav/server/server_cli.py we need to add an increased timeout (see example below):

`def _run_gunicorn(app, config, mode):`
`    options = {`
`        'bind': '%s:%s' % (config.get('host'), config.get('port')),`
`        'workers': 5,`
`        'timeout': 1200,`
`        "pidfile": config.get('pidfile'),`
`    }`

**Comment by shoeper** [comment]
I agree, but doesn't it allow an easy denial of service? Or can each worker handle multiple connections?

**Comment by eruditewriter** [comment]
I'm not certain on how many connections each worker can handle, however the value is already increased for the base server so replicating here shouldn't add to any security problems. I'm certain there's a more rational number than 30 seconds for this type of transfer that isn't so long it could shutdown the system.
