### ISSUE TITLE
Where is run_server?

### ISSUE THREAD

**Issue by COI-03** [haiwen/seafdav#59]
Hi 

I noticed that the entry point indicated inside the run.sh is `wsgidav.server.run_server`. But under `./wsgidav/server` I see no module named `run_server`. Can you tell me where that is?

**Comment by justjanne** [comment]
You’ll want to run "wsgidav.server.server_cli" instead, that’s where run_server appears to be now.

Disclaimer: Am not a member of the seafile team, just a random person.

**Comment by COI-03** [comment]
> You’ll want to run "wsgidav.server.server_cli" instead, that’s where run_server appears to be now.
> 
> Disclaimer: Am not a member of the seafile team, just a random person.

alright thx bro, closing this now.
