### ISSUE TITLE
Missing LastModified for Folders

### ISSUE THREAD

**Issue by MartB** [haiwen/seafdav#72]
https://github.com/haiwen/seafdav/blob/0ed426dd12caed8c85694fdc2c081dd68fecc86a/wsgidav/seafile_dav_provider.py#L358-L360

The absence of this could cause problems with sync clients that check for the last modified date of a parent folder.

I hacked an implementation together that works by doing the following:

```python
    def get_last_modified(self):
        cached_mtime = getattr(self.obj, 'last_modified', None)
        if cached_mtime:
            return cached_mtime
        
        try:
            mtimes = seafile_api.get_files_last_modified(self.repo.id, self.rel_path, 1)
        except SearpcError as e:
            raise DAVError(HTTP_INTERNAL_ERROR, e.msg)

        return max(mtime.last_modified for mtime in mtimes) if len(mtimes) else None
```

Whats the proper way to support this?
I set the traversal limit of get_files_last_modified to 1 to only get the last element, but I did not check  if it even returns more than 1 file. For now it does exactly what I want it to do.

**Comment by freeplant** [comment]
Fixed in https://github.com/haiwen/seafdav/pull/81
