### ISSUE TITLE
Authorization Bearer using SSO

### ISSUE THREAD

**Issue by Nithe14** [haiwen/seafdav#76]
Is it possible to  use a bearer token for authorization? I'm configuring Seafile for single sign-on (SSO) with the OpenID Connect protocol and a Keycloak server, but I keep getting a 401 error no matter what I try, even when using the SSO-authenticated user's `sessionid` cookie. It seems like only the `Authorization: Basic` method works for seafdav. Why is that, and how can I make seafdav work with SSO-delegated user?
Just to make it clear: You can't use basic authorization for SSO users as intended

**Comment by sphakka** [comment]
While having auth bearer implemented for seafdav would be great, it is indeed possible to use basic auth by setting a webdav-specific password. Cf. [seahub settings `ENABLE_WEBDAV_SECRET`](https://manual.seafile.com/config/seahub_settings_py/): once enabled, each user can set a password in their settings page -- `https://seafile.example.com/profile/#update-webdav-passwd`. Tested with Authelia OIDC, Nginx and davfs2 as client :).  Mind that your reverse proxy should be configured to bypass SSO auth for location `/seafdav`.

**Comment by Nithe14** [comment]
Thanks for the info @sphakka! It's working pretty well, and I hadn't noticed this option before. Unfortunately, it's not what I'm after because it means I'm sacrificing some security by skipping SSO and access tokens. It would be awesome to have bearer authorization in SeaDAV and use something like [`oidc-agent`](https://github.com/indigo-dc/oidc-agent), but maybe that's something to look forward to down the road. At least I can use my OIDC account with WebDAV

**Comment by Nithe14** [comment]
Any updates?

**Comment by freeplant** [comment]
We don't have a plan to implement this feature currently.
